debug: ${server_debug}

server:
    port: ${server_port}
    contextPath: /background

security:
    user:
        name: root
        password: root

spring:
#    jpa:
#        hibernate:
#            ddl-auto: none
#        show-sql: false
#    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
#        url: jdbc:mysql://${server_sql_ip}:3306/spring-boot?useUnicode=true&characterEncoding=UTF8&useCursorFetch=true&useSSL=false
#        driver-class-name: com.mysql.jdbc.Driver
#        username: ${server_sql_user}
#        password: ${server_sql_password}
#        schema: classpath:/sql/schema-mysql.sql
#        data: classpath:/sql/data-mysql.sql

#        druid:
#            filters: stat,wall,log4j                      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#            maxActive: 20
#            initialSize: 0
#            maxWait: 60000                                # 配置获取连接等待超时的时间
#            minIdle: 1
#            timeBetweenEvictionRunsMillis: 60000          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#            minEvictableIdleTimeMillis: 300000            # 配置一个连接在池中最小生存的时间，单位是毫秒
#            validationQuery: select 'x'
#            testWhileIdle: true
#            testOnBorrow: false
#            testOnReturn: false
#            poolPreparedStatements: true
#            maxPoolPreparedStatementPerConnectionSize: 20
#            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#            maxOpenPreparedStatements: 20
#
#            useGlobalDataSourceStat: true                 # 合并多个DruidDataSource的监控数据
    resources:
        cache-period: 15
#        static-locations: classpath:front-end,classpath:/META-INF/resources
#    thymeleaf:
#        suffix: .html
#        prefix: classpath:/templates/
    jackson:
        default-property-inclusion: non_null
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    http:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB


#mybatis:
#    configuration:
#        mapUnderscoreToCamelCase: true # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN 到经典 Java 属性名 aColumn 的类似映射。
#    type-aliases-package: com.housekeeper.service.background.database.model
#    mapper-locations: classpath:mapper/**/*.xml                   # mapper的xml文件

#TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
logging:
    level:
        root: WARN
        com.smart: WARN
        static: WARN

        org.springframework:
            data: WARN
            security: WARN


# JWT http://www.jianshu.com/p/6307c89fe3fa
jwt:
    secret: ${server_jwt_secret}
    tokenPrefix: "Bearer "
    header: "Authorization"
    accessToken:
        expiration: 1800 #access_token 有效期 单位:秒
    refreshToken:
        expiration: 7200 #refresh_token 有效期 单位:秒
    authRoute:
        login: "auth/login"
        register: "auth/register"
        refreshToken: "auth/refreshToken"
